name: Combined Pull Request

on: [workflow_dispatch, pull_request]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - name: Fetch develop branch so screenshotbot can access it
        run: |
          git fetch origin develop
      # - name: show git graph
      #   run: git show --format='%H %P' HEAD && git log --graph --all
      # - name: check merge
      #   run: git rev-parse HEAD &&  git merge-base 38181385c139952159a3cf69950f8ff658395efb `git rev-parse HEAD`
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install -r docs/requirements.txt
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
      - run: fastlane combined_pull_request
      - name: Validate Swagger and OpenAPI using Swagger CLI
        uses: mbowman100/swagger-validator-action@2.0
        with:
          files: webapi.yaml
    env:
      PR: true
      GIT_REPOSITORY_URL: ${{ github.repositoryUrl }}
      SCREENSHOTBOT_API_KEY:  ${{ secrets.SCREENSHOTBOT_API_KEY }}
      SCREENSHOTBOT_API_SECRET: ${{ secrets.SCREENSHOTBOT_API_SECRET }}
